In [1]:
#사용라이브러리
from tensorflow.keras.models import Sequential #신경망 생성
from tensorflow.keras.layers import Dense #퍼셉트론으로 구성된 신경망층 정의
import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn import datasets

In [2]:
#wine 데이터셋 가져오기
wine = datasets.load_wine()

In [3]:
# 딕셔너리 형태의 데이터
wine.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names'])

In [4]:
# 분석에 사용할 데이터
wine['data'] 

array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]])

In [5]:
wine['feature_names']

['alcohol',
 'malic_acid',
 'ash',
 'alcalinity_of_ash',
 'magnesium',
 'total_phenols',
 'flavanoids',
 'nonflavanoid_phenols',
 'proanthocyanins',
 'color_intensity',
 'hue',
 'od280/od315_of_diluted_wines',
 'proline']

In [6]:
#wine['data'] = 데이터프레임에 값
#wine['feature_names'] = 데이터프레임의 컬럼
X=pd.DataFrame(wine['data'],columns= wine['feature_names'])
X.shape

(178, 13)

In [7]:
# wine['target']

In [7]:
# 0, 1, 2
wine['target']

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [8]:
wine['target_names']

array(['class_0', 'class_1', 'class_2'], dtype='<U7')

In [9]:
# 정답 데이터 만들기
y = wine['target']

In [10]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [11]:
y=pd.get_dummies(y)

In [12]:
y

0  1  2
0    1  0  0
1    1  0  0
2    1  0  0
3    1  0  0
4    1  0  0
..  .. .. ..
173  0  0  1
174  0  0  1
175  0  0  1
176  0  0  1
177  0  0  1

[178 rows x 3 columns]

In [12]:
#모든데이터가 제대로 있는지 확인하면됨

In [13]:
X.shape

(178, 13)

In [14]:
# 모델 설계 
model = Sequential()
# 입력층
# input_dim = 입력 데이터의 특성 갯수
# 입력층에는 30개 뉴런을 생성할거야
#뉴런같은 경우는 모든 층마다 있음

model.add(Dense(30, input_dim = 13 , activation = 'relu'))


#은닉층
#신경망속에서 뉴런이 총 12개,#몇개 들어오는지 알 필요가 없음
model.add(Dense(12, activation='relu')) 
model.add(Dense(8, activation='relu'))
model.add(Dense(4, activation='relu'))

#출력층
#내가 마지막에 출력하는 데이터가 어떤것인지 출력하기위해서 sigmoid를 씀
#모델의 구조를 만들어줌
model.add(Dense(3,activation = 'sigmoid')) 

#뉴런은 늘리면 학습하는데 오래걸리고 줄이면 학습을 제대로 못하기때문에
#적당하게 쌓아야한다.
#뉴런의 갯수를 조금 줄여가는게 좋다 
#분류데이터이기 때문에 답이 마지막에 1개로 주어짐 1개를 출력하기 위해
#출력층에서는 한 개의 결과값을 출력해야함
#처음에는 다양한 방법으로 분석해보고 점점 줄여나가면서 한 개의 결과 값을 출력
# 중간 중간에 키웠다가 줄였다가 해도 상관 없지만 은닉층 마지막부분에서는 뉴런의
#수를 줄여나가는 게 좋습니다.
# 결과값과 출력층은 동일하게 하는게 좋다.
#와인데이터의 정답이 총 3개 이기때문에 3개의 출력갯수로 하면 1번와인이 정답확률,2번와인 정답확률,3번와인 정답확률로 출력을 함
#모델이 출력하는 갯수와 다르게 나타나면 오류가 뜸


In [21]:
# 모델 컴파일
# 설계한 모델을 실행할수 있도록 다양한 정보 입력
# loss: 손실함수(손실함수가 작을 수록 잘 설계된 모델로봄),오차
# optimizer : 경사하강법 종류(어떤 방법을 통해서 분석할 것이냐)
# metrics : 평가방법
#binary_crossentropy:카테고리가 2개인 경우
#categorical_crossentropy: 3개 이상의 경우
model.compile(loss = 'categorical_crossentropy',
             optimizer = 'adam',
             metrics = ['accuracy']) 


In [22]:
# 위에서 뉴런을 쌓은 것은 생각하는 방법이라고 할 수 있다.

# 모델 학습
# 문제,정답, 반복할 횟수,한번에 확인할 데이터 수
# batch_size 데이터를 분석 할 때 한 번에 10개씩 묶어서 분석
# batch_size 크게 잡으면 분석하는 속도가 빨라지고 작게 잡으면 속도가 오래 걸린다.
model.fit(X,y,epochs = 500, batch_size = 10)

Train on 178 samples
Epoch 1/500
178/178 [==============================] - 0s 2ms/sample - loss: 0.1064 - accuracy: 0.9719
Epoch 2/500
178/178 [==============================] - 0s 174us/sample - loss: 0.1193 - accuracy: 0.9551
Epoch 3/500
178/178 [==============================] - 0s 190us/sample - loss: 0.1006 - accuracy: 0.9607
Epoch 4/500
178/178 [==============================] - 0s 207us/sample - loss: 0.0707 - accuracy: 0.9831
Epoch 5/500
178/178 [==============================] - 0s 194us/sample - loss: 0.0590 - accuracy: 0.9831
Epoch 6/500
178/178 [==============================] - 0s 191us/sample - loss: 0.0668 - accuracy: 0.9831
Epoch 7/500
178/178 [==============================] - 0s 191us/sample - loss: 0.0564 - accuracy: 0.9888
Epoch 8/500
178/178 [==============================] - 0s 185us/sample - loss: 0.0624 - accuracy: 0.9775
Epoch 9/500
178/178 [==============================] - 0s 191us/sample - loss: 0.0887 - accuracy: 0.9775
Epoch 10/500
178/178 [==============

178/178 [==============================] - 0s 162us/sample - loss: 0.0695 - accuracy: 0.9831
Epoch 155/500
178/178 [==============================] - 0s 168us/sample - loss: 0.0592 - accuracy: 0.9775
Epoch 156/500
178/178 [==============================] - 0s 162us/sample - loss: 0.0531 - accuracy: 0.9831
Epoch 157/500
178/178 [==============================] - 0s 174us/sample - loss: 0.0470 - accuracy: 0.9888
Epoch 158/500
178/178 [==============================] - 0s 162us/sample - loss: 0.0551 - accuracy: 0.9775
Epoch 159/500
178/178 [==============================] - 0s 168us/sample - loss: 0.0739 - accuracy: 0.9719
Epoch 160/500
178/178 [==============================] - 0s 168us/sample - loss: 0.0921 - accuracy: 0.9663
Epoch 161/500
178/178 [==============================] - 0s 168us/sample - loss: 0.0519 - accuracy: 0.9831
Epoch 162/500
178/178 [==============================] - 0s 160us/sample - loss: 0.0567 - accuracy: 0.9831
Epoch 163/500
178/178 [============================

178/178 [==============================] - 0s 168us/sample - loss: 0.0537 - accuracy: 0.9831
Epoch 307/500
178/178 [==============================] - 0s 168us/sample - loss: 0.0354 - accuracy: 0.9888
Epoch 308/500
178/178 [==============================] - 0s 168us/sample - loss: 0.1132 - accuracy: 0.9663
Epoch 309/500
178/178 [==============================] - 0s 162us/sample - loss: 0.1014 - accuracy: 0.9663
Epoch 310/500
178/178 [==============================] - 0s 168us/sample - loss: 0.0716 - accuracy: 0.9719
Epoch 311/500
178/178 [==============================] - 0s 162us/sample - loss: 0.0616 - accuracy: 0.9831
Epoch 312/500
178/178 [==============================] - 0s 162us/sample - loss: 0.0656 - accuracy: 0.9719
Epoch 313/500
178/178 [==============================] - 0s 157us/sample - loss: 0.0471 - accuracy: 0.9775
Epoch 314/500
178/178 [==============================] - 0s 160us/sample - loss: 0.0467 - accuracy: 0.9775
Epoch 315/500
178/178 [============================

178/178 [==============================] - 0s 162us/sample - loss: 0.0472 - accuracy: 0.9831
Epoch 459/500
178/178 [==============================] - 0s 162us/sample - loss: 0.0373 - accuracy: 0.9831
Epoch 460/500
178/178 [==============================] - 0s 168us/sample - loss: 0.1095 - accuracy: 0.9607
Epoch 461/500
178/178 [==============================] - 0s 162us/sample - loss: 0.0902 - accuracy: 0.9663
Epoch 462/500
178/178 [==============================] - 0s 168us/sample - loss: 0.0529 - accuracy: 0.9831
Epoch 463/500
178/178 [==============================] - 0s 168us/sample - loss: 0.0420 - accuracy: 0.9888
Epoch 464/500
178/178 [==============================] - 0s 162us/sample - loss: 0.0434 - accuracy: 0.9888
Epoch 465/500
178/178 [==============================] - 0s 157us/sample - loss: 0.0435 - accuracy: 0.9831
Epoch 466/500
178/178 [==============================] - 0s 168us/sample - loss: 0.0478 - accuracy: 0.9775
Epoch 467/500
178/178 [============================